<%
pods = {}
p('pods').each { |pod| pods[pod.to_s] = true }
-%>
<% if pods['scheduler'] %>
---
kind: Pod
apiVersion: v1
metadata:
  name: kube-scheduler
  namespace: kube-system

spec:
  hostNetwork: true
  containers:
    - name: kube-scheduler
      image: <%= link('api').p('images.k8s') %>
      command:
        - /kube-scheduler
        - --kubeconfig=/data/kubeconfig/scheduler.kubeconfig
        - --leader-elect=true
        - --v=2

      volumeMounts:
        - name: data
          mountPath: /data
          readOnly: true

      livenessProbe:
        initialDelaySeconds: 15
        timeoutSeconds: 5
        httpGet:
          scheme: HTTP
          host:   127.0.0.1
          port:   10251
          path:   /healthz

  volumes:
    - name: data
      hostPath:
        path: /var/vcap/data/k8s
<% end %>
