name: tinynetes

instance_groups:
  - name:      k8s
    instances: 1
    azs:       [z1]
    vm_type:   default
    stemcell:  default

    persistent_disk_type: default

    networks:
      - name: default

    jobs:
      - name: control
        release: k8s
        properties:
          cluster:
            name: tinynetes
            ip: 127.0.0.1
          encryption:
            key: ((encryption-key1))
          tls:
            ca:
              certificate: ((tls-ca.certificate))
              key:         ((tls-ca.private_key))
            admin:
              certificate: ((tls-admin.certificate))
              key:         ((tls-admin.private_key))

      - name: etcd
        release: k8s
        properties:
          debug: yes

      - name: runtime-runc
        release: k8s
      - name: kubelet
        release: k8s
        properties:
          pod-cidr: 10.200.250.0/24

      - name: jumpbox
        release: k8s
      - name: status-of-etcd
        release: k8s

variables:
  - name: tls-ca
    type: certificate
    options:
      is_ca: yes
      common_name: ca

  - name: tls-admin
    type: certificate
    options:
      ca: tls-ca
      common_name: admin

  - name: encryption-key1
    type: password
    options:
      length:          32
      include_special: yes

update:
  canaries: 1
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-120000
  update_watch_time: 1000-120000

stemcells:
  - alias:   default
    os:      ubuntu-xenial
    version: latest

releases:
  - name:    k8s
    version: latest
