name: tinynetes

instance_groups:
  - name:      k8s
    instances: 1
    azs:       [z1]
    vm_type:   default
    stemcell:  default

    persistent_disk_type: default

    networks:
      - name: default

    jobs:
      - name: api
        release: k8s
        properties:
          cluster:
            name: tinynetes
            ip: 127.0.0.127
          encryption:
            key: ((encryption-key1))
          tls:
            ca:
              certificate: ((tls-ca.certificate))
              key:         ((tls-ca.private_key))
            api:
              certificate: ((tls-api.certificate))
              key:         ((tls-api.private_key))
            controller-manager:
              certificate: ((tls-controller-manager.certificate))
              key:         ((tls-controller-manager.private_key))
            scheduler:
              certificate: ((tls-scheduler.certificate))
              key:         ((tls-scheduler.private_key))
            service-accounts:
              certificate: ((tls-service-accounts.certificate))
              key:         ((tls-service-accounts.private_key))
            kubelet:
              certificate: ((tls-kubelet.certificate))
              key:         ((tls-kubelet.private_key))
            proxy:
              certificate: ((tls-proxy.certificate))
              key:         ((tls-proxy.private_key))

      - name: etcd
        release: k8s
      - name: controller-manager
        release: k8s
      - name: scheduler
        release: k8s

      - name: runtime-runc
        release: k8s
      - name: proxy
        release: k8s
      - name: kubelet
        release: k8s

variables:
  - name: tls-ca
    type: certificate
    options:
      is_ca: yes
      common_name: ca

  - name: tls-admin
    type: certificate
    options:
      ca: tls-ca
      common_name: admin

  - name: tls-api
    type: certificate
    options:
      ca: tls-ca
      common_name:  kubernetes
      organization: kubernetes
      alternative_names:
        - kubernetes.default
        - 127.0.0.1
        - 10.45.45.101
        - 10.45.45.102
        - 10.45.45.103
        - 10.92.92.101
        - 10.92.92.102
        - 10.92.92.103

  - name: tls-kubelet
    type: certificate
    options:
      ca: tls-ca
      common_name:  system:node:node
      organization: system:nodes
      alternative_names:
        - 127.0.0.1
        - 10.45.45.10
        - 10.92.92.10

  - name: tls-controller-manager
    type: certificate
    options:
      ca: tls-ca
      common_name:  system:kube-controller-manager
      organization: system:kube-controller-manager

  - name: tls-proxy
    type: certificate
    options:
      ca: tls-ca
      common_name:  system:kube-proxy
      organization: system:node-proxier

  - name: tls-scheduler
    type: certificate
    options:
      ca: tls-ca
      common_name:  system:kube-scheduler
      organization: system:kube-scheduler

  - name: tls-service-accounts
    type: certificate
    options:
      ca: tls-ca
      common_name:  service-accounts
      organization: kubernetes

  - name: encryption-key1
    type: password
    options:
      length:          32
      include_special: yes

update:
  canaries: 1
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-120000
  update_watch_time: 1000-120000

stemcells:
  - alias:   default
    os:      ubuntu-xenial
    version: latest

releases:
  - name:    k8s
    version: latest
